---
- name: Play to create EC2 instance.
  hosts: localhost
  connection: localhost
  gather_facts: True

  vars_files:
    - ~/aws_keys.yml
    - group_vars/all
    
  tasks:
    - name: Create an ec2 instance
      ec2:
         aws_access_key: "{{ AWS_ACCESS_KEY_ID }}"
         aws_secret_key: "{{ AWS_SECRET_ACCESS_KEY }}"
         region: "{{ region }}"   
         key_name: "{{ ssh_keyname }}"
         group: "{{ security_group }}"
         instance_type: "{{ instance_type }}"
         image: "{{ ami_id }}"
         wait: true
         count: 1
         vpc_subnet_id: "{{ vpc_name }}"
    - debug: var=ansible_host
