---
- name: Change instances state by tag
  hosts: localhost
  gather_facts: yes
  vars_files:
    - ~/keys.yml

  tasks:
      - name: Create a new EC2 key
        ec2_key:
            name: ansible-key
            region: us-east-1
        register: ec2_key_result
 
      - name: Save private key
        copy: content="{{ ec2_key_result.key.private_key }}" dest="./aws.demo.pem" mode=0600
        when: ec2_key_result.changed
